export const EjerOraciones = {
  PALA: [
    "El lápiz es azul.",
    "La lupa de mamá.",
    "La pala es alta.",
    "Luz es mi mamá.",
    "Yo pico la papa.",
    "Yo leo libros a Lupe.",
    "Lulú y Paula pelean.",
    "Mi papá lee un libro.",
    "La pala de papá.",
    "La lupa es lila.",
    "Mamá pela la papa.",
    "El león es grande.",
    "La pila es chica.",
    "La pipa de mi papá.",
    "La ola es muy alta.",
    "Las palapas del parque.",
    "La piel de mamá es bonita.",
    "Ayer oí la pelea de los vecinos.",
    "Yo leí los libros de mamá ayer.",
    "Yo apilo los palos del patio.",
    "Mi perro es leal.",
    "El apio para la comida.",
    "El aula de clases.",
    "La pelea en la calle.",
    "Una papa de pilón.",
    "Lulú y Pepe usan la lupa.",
    "Lola pule los palos.",
    "Yo le leo a la niña.",
    "El pie de mamá."
  ],
  PIÑATA:[
    "El palo para la piñata.",
    "El niño patea la pelota.",
    "La pileta tiene agua.",
    "Pepe tapa la lata.",
    "La lata de elotes.",
    "La paleta de piña.",
    "La piñata está rota en el piso.",
    "Los niños juegan con la pelota.",
    "La pata de la mesa.",
    "Papá y yo comemos elotes.",
    "Mi mamá usa leña para hacer la comida.",
    "La tía Talía es muy mala.",
    "Los papás de Toño son muy mañosos.",
    "El pétalo de una rosa.",
    "El altar en la calle es muy alto.",
    "El peleador usa los puños para pelear.",
    "El otoño está muy cerca.",
    "Las tías de papá se tiñen el pelo con mamá.",
    "La tapa del café.",
    "El auto de los tíos es muy útil.",
    "La piñata es para tú fiesta.",
    "Te tomé unas paletas de la lata.",
    "A ti te gustan las pelotas.",
    "A tu tío le gustan los autos.",
    "Toño y Lalo son tapatíos.",
    "Lalo y Paola son pilotos de autos.",
  ],
  FAMILIA:[
    "La familia de mi papá es mañosa.",
    "A mí me gusta la miel.",
    "El alma de mi amado.",
    "Marta y Tomas fuman.",
    "La foto de mi pie en la cama.",
    "La fila de los tamales y el atole.",
    "La foto de mi familia está muy bonita.",
    "El tamaño de la fuente es muy grande.",
    "El amuleto para el amor es muy útil.",
    "Mi mamá está mala de los pies.",
    "Emilio es muy fuerte.",
    "Paloma fue a la feria.",
    "El filo del arma es fatal.",
    "La muela de mi mamá.",
    "Yo te firmo las hojas.",
    "La fama de los autos es muy mala.",
    "Afuera está la feria de la ciudad.",
    "Ayer fue la fiesta de Felipe y Amor.",
    "La tierra es fértil.",
    "Yo fomento la unión familiar.",
    "La forma de la mesa es mala.",
    "El foro es muy grande.",
    "La fórmula de la receta es muy útil.",
    "La maleta está afuera lista para ti.",
    "Mi perro es fiel.",
    "La milpa de elotes.",
    "La lata de maíz.",
    "La meta es terminar la escuela.",
    "El mole es mío.",
    "Mi tío aumentó la fecha límite.",
    "El olfato de los perros es muy bueno.",
    "La tele es mía.",
    "La familia es lo más importante.",
  ],
  BASURA:[
    "Aurora sube al segundo piso.",
    "Las patas de la mesa son muy altas.",
    "El sábado hay fiesta con mi familia.",
    "La abuela no salió en la foto.",
    "Las armas son muy peligrosas.",
    "No me gustan las piñas, pero a mi mamá sí.",
    "Mi tía es mesera en el salón de fiestas.",
    "El mar es muy salado.",
    "No pises la basura en la calle.",
    "Sebastián besó a su esposa.",
    "La masa para hacer los tamales.",
    "El aire que respiramos es limpio.",
    "Esas rosas son para mi mamá.",
    "Toma al toro por los cuernos.",
    "El muro esta muy alto para pintarlo.",
    "Esas palas las usan los albañiles.",
    "Las bacterias del agua son dañinas.",
    "Esas paletas son para mis familiares.",
    "Esos autos van por la autopista.",
    "Esa es la peor moto para ti.",
    "La alarma nos alertó del robo.",
    "Las señales son para parar el auto.",
    "Tira la basura en su lugar.",
    "Los bebes de Ruth son muy amorosos.",
    "La tubería para el muro es muy barata.",
    "Los sabios de la montaña.",
    "La salsa tiene mucha sal.",
    "El ratero subió por la tubería.",
    "Para el frio uso un suéter.",
    "Mi suerte para el amor es lo peor.",
    "El titulo del tema es raro.",
    "La astucia del zorro es de temer.",
    "La rosa es para mis abuelos."
  ],
  MEDICINA:[
    "Ya puedo leer el abecedario.",
    "Enamorarse es lo más bonito del mundo.",
    "La luna sale en las noches.",
    "El diente de Saúl esta por caer.",
    "Diana no sabe el alfabeto.",
    "Unas nubes son grandes y las demás son chicas.",
    "Hay un recado en la mesa para Benito.",
    "La medicina se compra en la farmacia.",
    "La salud de todos es importante.",
    "La estación del año que entra es otoño.",
    "Reímos como niños después del juego.",
    "Mi marido es muy amoroso.",
    "Unas donas son rellenas y otras de dulce.",
    "La reunión apenas va a empezar.",
    "En el pedir está el dar.",
    "Hay un forastero en la ciudad.",
    "Mi mano fuerte es la derecha.",
    "No me gusta el durazno ni la manzana.",
    "El camino hacia la ciudad esta abierta en la mañana.",
    "El nopal con la salsa es muy delicioso.",
    "Los abuelitos de Antonio son comediantes.",
    "Paulina y Natalia no son amigas, ni se conocen.",
    "Necesito seis monedas para el autobús.",
    "Una rosa para todas mis tías.",
    "Un pastel para Elena.",
    "Todos para uno y uno para todos.",
    "El cielo está muy bonito.",
    "Hoy es un día muy soleado.",
    "No le tengo miedo a las arañas ni a las ratas.",
    "La receta de mi mamá es fácil de hacer.",
    "La solución de mis problemas no es el dinero.",
    "Daniel anuló la boda un día antes.",
    "Nanci fue muy rápida durante la carrera.",
    "Todos los niños saludan a los ancianos en la calle.",
    "Una rosa para mis abuelos.",
    "El beneficio de la medicina no tiene precio.",
    "El municipio tiene muchos policías en las calles.",
    "El médico me recetó paracetamol.",
    "El ascensor del metro es muy eficiente."
  ],
  CASA:[
    "La casa de mi mamá es café.",
    "La caza de animales no está permitida.",
    "Mi perro no es feo, para que lo sepas.",
    "El mecánico repara el carro azul.",
    "La taza de Camila es más grande que la mía.",
    "¿Qué camino tomas para ir a San Damián?",
    "La cabeza del alfiler es muy pequeña.",
    "Las copias cuestan mucho dinero.",
    "La máquina de coser es muy rápida.",
    "La azúcar alta es causa de diabetes.",
    "Carlos tiene un corazón de pollo.",
    "El médico me recetó un antibiótico.",
    "¡Acomoda las cosas, que casi llegan mis papás!",
    "¡Alza los pies! Estoy limpiando.",
    "La comida está caliente.",
    "Dame tequila para olvidar.",
    "El fumar causa cáncer.",
    "El té de canela es delicioso.",
    "El pulque, la bebida de los dioses.",
    "Paulina miró en la tele que hay descuentos en el supermercado.",
    "El alquiler que pagas es muy caro.",
    "Cura la cortada que tienes en la mano.",
    "Yo quiero a toda mi familia actual.",
    "Como más dulces con mi abuelita que con mi tía.",
    "¿Cómo está la familia?",
    "¿Acaso has ido a otro estado?",
    "No con cualquiera salgo a caminar.",
    "La cascara de zanahoria es muy rica.",
    "El zorro es muy astuto, aunque no lo sepas.",
    "El zumbido en mis oídos no es bueno.",
    "La esperanza es lo último que muere.",
    "Esta zona de la ciudad es sana.",
    "Deslizar la tarjeta para entrar al estacionamiento.",
    "En la azotea están las calabazas.",
    "El pozole no tiene picantes.",
    "Que la luz del sol es dañina para la salud.",
  ],
  VACUNA:[
    "El motivo de la cita es para platicar.",
    "El verano empieza en marzo.",
    "El día de muertos se festeja en noviembre.",
    "El lugar donde vivo esta cerca de la ciudad.",
    "Volar ya no solo es para las aves.",
    "La violencia no es el único camino.",
    "Aún no hay vacunas para el VIH.",
    "La vida continua sin nosotros.",
    "Viviana cambio el lugar donde vive.",
    "Victor se va de vacaciones en verano.",
    "Eva tiene un amuleto muy valioso.",
    "El oro tiene un valor muy alto.",
    "La lavadora no funciona.",
    "¡Saca la vela! No veo.",
    "Las vitaminas son importantes para la salud.",
    "El veneno de las víboras es letal.",
    "Visita al veterinario y compra la medicina.",
    "Lava el vaso bien.",
    "El velorio de Valentina es el viernes.",
    "La variedad de panes es demasiado.",
    "Hay que vaciar la basura en la bolsa.",
    "La envidia no es buena, mata el alma y la envenena.",
    "La pólvora se usa para muchas cosas.",
    "Ella me cautivo con su sonrisa.",
    "Un tequila de vez en cuando para calmar las penas.",
    "La voz de tu interior.",
    "Octavio es un vividor sin beneficio.",
    "Comprar votos es un delito.",
    "Encerrar la respuesta también es válido.",
    "Una vez vi un gato volando en la azotea.",
    "Lavar la ropa es tarea de todos.",
    "Vivir sin ti es posible."
  ],
  CANTINA:[
    "¿Quién te acompaña en tu visita?",
    "Desde hace tiempo que no salimos de la ciudad.",
    "He visto muchas cosas en mi vida.",
    "La adolescencia es la mejor etapa en la vida.",
    "La respuesta de la adivinanza es difícil.",
    "Burlar la ley no está bien visto.",
    "Los impuestos son muy importantes para el país.",
    "La cena del sábado estuvo muy rica.",
    "Nunca cambies el amor por dinero.",
    "La alarma sonará el miércoles por la mañana.",
    "Todos recibimos un adelanto en navidad.",
    "Antes de ti, no conocía el amor.",
    "Adolfo es muy romántico con sus novias.",
    "Aquel ruido alto es de la tienda cerca de la casa.",
    "Mi hermana hizo la cena de hoy.",
    "En la papelería venden hilo para coser.",
    "Los huesos son muy duros.",
    "El señor Leonardo está enfermo de los huesos.",
    "Adentro de la casa, está la herramienta.",
    "¿Quién es el vecino? ¿Lo conoces?",
    "La víctima del robo no tuvo mucha suerte.",
    "Las manzanas son deliciosas.",
    "Adopta una mascota, te harán compañía.",
    "Revisa la caducidad de las bebidas que compras.",
    "Conocer los números es muy importante para el trabajo.",
    "La pierna de cerdo es muy cara.",
    "Mañana voy a renunciar.",
    "Ponle hielo a las bebidas.",
    "¿Con quién te vas a casa?",
    "Nueve es mi numero de la suerte.",
    "Es horrible lo que le hicieron.",
    "Necesito harina de trigo para la cocina.",
    "El huevo esta muy caro estos días.",
    "Hervir el agua antes de tomarlo.",
    "Mi hermana se va a casar el sábado.",
    "La historia de mi país es interesante.",
    "Nos vemos a la misma hora que ayer.",
    "El papá está ausente por el trabajo.",
    "El cáncer es curable si se detecta a tiempo.",
    "El cambio a veces es bueno.",
  ],
  MERCADO:[
    "Karen esta harta de comer sopa todos los días.",
    "Karina esta ansiosa de morder una manzana.",
    "Homero fue al mercado a comprar huevos.",
    "El miércoles visite a mis hermanos.",
    "La carne de cerdo se mete al horno.",
    "No hay perros morados, estas soñando.",
    "Los murciélagos son animales nocturnos.",
    "Nadie mira el partido en la fiesta.",
    "La marea es muy hostil.",
    "Fui al mandado por la mañana y compré cacahuates.",
    "Compra una caja de mermelada.",
    "Todos los días hay humedad en la casa.",
    "Zanahorias y papas son verduras que hay en la comida.",
    "La hipoteca de la casa es para 20 años.",
    "La habitación de arriba no es para mis hermanos.",
    "El hospital está muy bien equipado.",
    "Yo anhelo tener un negocio.",
    "El búho es un animal muy interesante.",
    "Las bebidas alcohólicas se toman con medida.",
    "Olvide comprar el hilo que mamá me pidió.",
    "El martes es el día límite de pago.",
    "Las mariposas viajan mucho desde el norte.",
    "No puedo comer los mariscos del mercado.",
    "Yo no puedo marcar la hora de salida.",
    "Hay muchos participantes para el maratón.",
    "El mercurio es muy peligroso."
  ],
  TRABAJO:[
    "El trabajo de los niños es jugar.",
    "Atrás del cajón se encuentra la hoja a firmar.",
    "Javier hace ejercicio todos los jueves.",
    "El girasol siempre apunta hacia el sol.",
    "Benjamín no tiene pareja actualmente.",
    "El jardín está lleno de mariquitas.",
    "Afuera de la casa hay un altar de la virgen.",
    "El gerente esta trabajando con sus empleados.",
    "En la tlapalería venden palas.",
    "Mis papás están jubilados.",
    "Juntos, pero no revueltos.",
    "Los atletas entrenan muy duro.",
    "La jefatura de policía está cerca de aquí.",
    "Entre nosotros hay un traidor.",
    "Muchos pájaros viven encerrados dentro de una jaula.",
    "Fíjate si ya puso la marrana.",
    "El diablo sabe más por viejo que por diablo.",
    "La junta de la escuela es el jueves.",
    "Saca la carne del congelador.",
    "La imaginación no tiene límites.",
    "La tradición del día de muertos es hermosa.",
    "Mañana hay ajuste de sueldos en el trabajo.",
    "German trajo muchos dulces para los niños.",
    "La energía eléctrica es muy importante.",
    "Los jóvenes están llenos de energía.",
    "¡Que nadie mire hacia atrás! Es una orden.",
    "La ventaja de ser mujer es tener siempre la razón.",
    "El refresco de naranja es muy delicioso.",
    "Ese genio no entiende con palabras.",
    "Los brazos del jugador son muy grandes.",
    "El entrenador hace ejercicio todos los días.",
    "La brisa del mar me toca la piel.",
    "Su hermosura es abrumadora.",
    "La brújula marca hacia el norte.",
    "En breve comenzamos la reunión.",
    "Este salario bruto no es suficiente.",
    "La broma para mis compañeros fue muy mala.",
    "Hay un bloqueo en la avenida.",
    "No hay blanqueador para la ropa.",
    "La blusa de la tienda esta hermosa.",
    "El tren transporta leña."
  ],
  TORTILLA:[
    "La tortilla de allá esta mejor.",
    "Mi nombre es Daniel y mi apellido es Suarez.",
    "El martillo que busca el albañil está aquí.",
    "Voy a llamar a una patrulla para la pandilla de la esquina.",
    "Aquella pareja se ve muy feliz.",
    "Los pasillos del hospital son muy callados.",
    "El camello tiene una huella muy particular.",
    "El mayor de los hermanos vive allí, en la esquina.",
    "La cebolla nos hace llorar al cortarlo.",
    "La silla tiene cuatro patas.",
    "El lunes atropellaron al vecino.",
    "Es maravillosa la vida que tenemos.",
    "El detalle es que no sabemos dónde vive.",
    "Solo nos queda llorar.",
    "El alumno humilló al profesor que lo molestaba.",
    "La mayoría de los zapatos son de aquella pareja.",
    "El proyecto de Juan es sencillo.",
    "El hoyo fue llenado con basura.",
    "El caballo es muy rápido",
    "Me gusta comer tlacoyos por la mañana.",
    "El brillo de la lampara es muy molesto.",
    "Los muebles son suyos.",
    "La fila para las tortillas.",
    "Hay que apoyar a la familia, a pesar de todo.",
    "Los nombres se escriben con mayúscula.",
    "El pellejo del pollo no se come.",
    "El cielo esta despejado, hoy no lloverá.",
    "El tornillo no está apretado.",
    "La bolsa de las servilletas está en la mesa, pero ya no hay.",
    "Las pastillas de los medicamentos saben feo.",
    "La tarjeta del banco es dorada.",
    "La capilla se terminó apenas entrando enero.",
    "La varilla está torcida para moverla más fácil.",
    "La ballena azul es un mamífero muy grande.",
    "El villano de la película es muy torpe.",
    "La tuerca está floja.",
    "Hay que terminar la tarea.",
    "Compartir tus juguetes habla bien de ti.",
    "Mi portafolio favorito es el morado.",
    "Tramitar estos servicios no es tarea fácil.",
  ],
  LECHE:[
    "Chiflar a la gente es de mal gusto.",
    "El bache de la avenida se hizo por el agua.",
    "El perro chico no es mío.",
    "En Xochimilco hay trajineras para los visitantes.",
    "La mancha de café se quita al lavarlo muy bien.",
    "Anoche viví un momento inolvidable.",
    "La plancha de mi mamá ya no funciona.",
    "Mi sobrino fue rechazado de la universidad.",
    "El techo del baño esta por caerse.",
    "Antes se quemaban a las brujas en las hogueras.",
    "Las vecinas os muy chismosas.",
    "No le eches muchos chiles a la salsa.",
    "Si no sabes cómo ponerte hoy ¡Ponte trucha!",
    "El otro equipo busca la revancha.",
    "El auto chocó con la pared.",
    "Las flores se marchitaron por el calor.",
    "El atole de chocolate es de lo más sabroso.",
    "Toda casa debería de tener un machete.",
    "La salchicha de pavo es más económica.",
    "Las cucharas son de metal.",
    "La leche es esencial en la alimentación de los bebés.",
    "La leche contiene calcio para los huesos.",
    "En la mañana desayuno leche y huevos.",
    "Los niños llevan sus libros en la mochila.",
    "Hay muchos bichos raros en el jardín.",
    "Fui a cobrar el cheque de mi trabajo.",
    "Los ranchos son tierras muy grandes.",
    "Los chicles son de muchos sabores y colores.",
    "En las noticias hablaron de la marcha de mujeres.",
    "Comer chorizo con arroz es muy común en mi tierra.",
    "Me fui de pachanga toda la semana."
  ],
  GUITARRA:[
    "La guitarra es un instrumento musical.",
    "Con el dialogo podemos arreglar nuestros problemas.",
    "A alguien que conozco no le gusta el aguachile.",
    "El águila caza roedores.",
    "El aguacero de ayer fue muy horrible.",
    "Hay algo que me molesta mucho.",
    "La sierra es una herramienta que usan los leñadores.",
    "La carrera tiene un límite de treinta minutos.",
    "Mi novia me regaló unos chocolates para mi cumpleaños.",
    "Hay un águila en el escudo nacional.",
    "Tengo un gato grande por mascota, es hembra.",
    "La guerra no es un camino para seguir.",
    "El dueño de ese perro lo amarro en el poste.",
    "La garantía de la lavadora aún está vigente.",
    "El regalo de mis padres está horrible.",
    "Dinero y vergüenza son dos cosas que no tengo.",
    "No logro aguantar la gotera en la sala.",
    "La gasolina es muy importante para los carros.",
    "Lo correcto es gobernar con justicia.",
    "¿Alguien conoce a Gabriela?",
    "Hice mi tarea, igual que los demás.",
    "Olvide algo en la casa, voy a recogerlo.",
    "Mi amigo logró aguantar un año sin tomar.",
    "Ayer alguien gastó mucho en las ofertas de la tienda.",
    "Socorro no logro llegar a la meta en la carrera.",
  ],
  MEXICO:[
    "En México halamos español.",
    "México tiene gran variedad de climas.",
    "La flora y fauna es muy extensa y diversa en nuestro país.",
    "Felix y Ximena tienen mucha experiencia en su trabajo.",
    "Xochitl reflexiona acerca de su decisión que tomó anoche.",
    "El examen de ayer estuvo muy difícil.",
    "En la exhibición del museo había muchos animales antiguos.",
    "Me gusta mucho exprimir limones.",
    "Mi madre es muy exagerada, imagina muchas cosas.",
    "Las relaciones toxicas son cosas que debemos evitar.",
    "El nuevo empleado necesita que le expliquen muchas cosas.",
    "El oxigeno es muy importante para los humanos.",
    "El boxeador usa guantes para pelear.",
    "En épocas de vacaciones, nos visitan muchos extranjeros.",
    "El petróleo se extrae en las plataformas petroleras.",
    "¡Como extraño a mi amiga de la infancia!",
    "El consumo de alcohol en exceso es dañino para la salud.",
    "Hay que respetar los espacios exclusivos para discapacitados.",
    "Mi esposo no es muy expresivo.",
    "Mis hijos son de excelencia académica.",
    "Agrega la cantidad exacta para el experimento.",
  ]
}